<a href="https://colab.research.google.com/github/asyhar22/kalbe_farma_ds/blob/main/VIX_Kalbe_Nutritionals_merge_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [1]:
customer_url = "https://raw.githubusercontent.com/asyhar22/kalbe_farma_ds/main/DATA/Case%20Study%20-%20Customer.csv"
store_url = "https://raw.githubusercontent.com/asyhar22/kalbe_farma_ds/main/DATA/Case%20Study%20-%20Store.csv"
product_url = "https://raw.githubusercontent.com/asyhar22/kalbe_farma_ds/main/DATA/Case%20Study%20-%20Product.csv"
transaction_url = "https://raw.githubusercontent.com/asyhar22/kalbe_farma_ds/main/DATA/Case%20Study%20-%20Transaction.csv"

In [5]:
customer_table = pd.read_csv(customer_url, delimiter=";")
store_table = pd.read_csv(store_url, delimiter=";")
product_table = pd.read_csv(product_url, delimiter=";")
transaction_table = pd.read_csv(transaction_url, delimiter=";")

In [6]:
customer_table.head(5)

   CustomerID  Age  Gender Marital Status Income
0           1   55       1        Married   5,12
1           2   60       1        Married   6,23
2           3   32       1        Married   9,17
3           4   31       1        Married   4,87
4           5   58       1        Married   3,57

In [7]:
store_table.head(5)

   StoreID         StoreName GroupStore           Type   Latitude   Longitude
0        1     Prima Tendean      Prima   Modern Trade       -6,2  106,816666
1        2  Prima Kelapa Dua      Prima   Modern Trade  -6,914864  107,608238
2        3        Prima Kota      Prima   Modern Trade  -7,797068  110,370529
3        4       Gita Ginara       Gita  General Trade  -6,966667  110,416664
4        5           Bonafid       Gita  General Trade  -7,250445  112,768845

In [8]:
product_table.head(5)

  ProductID   Product Name  Price
0        P1      Choco Bar   8800
1        P2  Ginger Candy    3200
2        P3       Crackers   7500
3        P4    Potato Chip  12000
4        P5       Thai Tea   4200

In [9]:
transaction_table.head(5)

,TransactionID,CustomerID,Date,ProductID,Price,Qty,TotalAmount,StoreID
0,TR11369,328,01/01/2022,P3,7500,4,30000,12
1,TR16356,165,01/01/2022,P9,10000,7,70000,1
2,TR1984,183,01/01/2022,P1,8800,4,35200,4
3,TR35256,160,01/01/2022,P1,8800,7,61600,4
4,TR41231,386,01/01/2022,P9,10000,1,10000,4

In [10]:
df = pd.merge(transaction_table, product_table, on="ProductID", how='left')
df = pd.merge(df, customer_table, on="CustomerID", how='left')
df = pd.merge(df, store_table, on="StoreID", how='left')
df.head(5)

,TransactionID,CustomerID,Date,ProductID,Price_x,Qty,TotalAmount,StoreID,Product Name,Price_y,Age,Gender,Marital Status,Income,StoreName,GroupStore,Type,Latitude,Longitude
0,TR11369,328,01/01/2022,P3,7500,4,30000,12,Crackers,7500,36,0,Married,"10,53",Prestasi Utama,Prestasi,General Trade,"-2,990934","104,756554"
1,TR16356,165,01/01/2022,P9,10000,7,70000,1,Yoghurt,10000,44,1,Married,"14,58",Prima Tendean,Prima,Modern Trade,"-6,2","106,816666"
2,TR1984,183,01/01/2022,P1,8800,4,35200,4,Choco Bar,8800,27,1,Single,"0,18",Gita Ginara,Gita,General Trade,"-6,966667","110,416664"
3,TR35256,160,01/01/2022,P1,8800,7,61600,4,Choco Bar,8800,48,1,Married,"12,57",Gita Ginara,Gita,General Trade,"-6,966667","110,416664"
4,TR41231,386,01/01/2022,P9,10000,1,10000,4,Yoghurt,10000,33,0,Married,"6,95",Gita Ginara,Gita,General Trade,"-6,966667","110,416664"

In [11]:
df.to_excel("merged_data.xlsx", index=False)